import React from "react";
import { Still } from "remotion";
import { PAGE_WIDTH, PAGE_HEIGHT } from "./pageSize";
import { ACover, AForeword, ATOC, AVonChris, AKapitel1, ARecipe } from "./directions/a";
import { BCover, BForeword, BTOC, BVonChris, BKapitel1, BRecipe } from "./directions/b";
import { CCover, CForeword, CTOC, CVonChris, CKapitel1, CRecipe } from "./directions/c";
import {
  DCover,
  DTOC,
  DForeword,
  DPart1Divider,
  DVonChris,
  DVonChris2,
  DKapitel1,
  DKapitel2,
  DKapitel3,
  DKapitel3b,
  DChapterDivider,
  DKapitel4,
  DKapitel5,
  DKapitel6,
  DKapitel6b,
  DPart3Divider,
  DKapitel7,
  DKapitel8,
  DPart4Divider,
  DKapitel9a,
  DKapitel9b,
  DRecipe,
  DRecipe2,
  DRecipe3,
  DKapitel11a,
  DKapitel11b,
  DFAQ,
  DAnhangIntro,
  DTriggerFoodCheck,
  DNotfallkarte,
  DEinkaufslisteDruck,
  DPantry,
  DUeberChris,
  DSchlusswort,
  DBackmatter,
} from "./directions/d";

const stills: { id: string; component: React.FC }[] = [
  { id: "a-cover", component: ACover },
  { id: "a-toc", component: ATOC },
  { id: "a-foreword", component: AForeword },
  { id: "a-von-chris", component: AVonChris },
  { id: "a-kapitel1", component: AKapitel1 },
  { id: "a-recipe", component: ARecipe },
  { id: "b-cover", component: BCover },
  { id: "b-toc", component: BTOC },
  { id: "b-foreword", component: BForeword },
  { id: "b-von-chris", component: BVonChris },
  { id: "b-kapitel1", component: BKapitel1 },
  { id: "b-recipe", component: BRecipe },
  { id: "c-cover", component: CCover },
  { id: "c-toc", component: CTOC },
  { id: "c-foreword", component: CForeword },
  { id: "c-von-chris", component: CVonChris },
  { id: "c-kapitel1", component: CKapitel1 },
  { id: "c-recipe", component: CRecipe },

  { id: "d-01-cover", component: DCover },
  { id: "d-02-toc", component: DTOC },
  { id: "d-03-foreword", component: DForeword },
  { id: "d-04-von-chris", component: DVonChris },
  { id: "d-05-von-chris2", component: DVonChris2 },
  { id: "d-06-part1-divider", component: DPart1Divider },
  { id: "d-07-kapitel1", component: DKapitel1 },
  { id: "d-08-kapitel2", component: DKapitel2 },
  { id: "d-09-kapitel3", component: DKapitel3 },
  { id: "d-10-kapitel3b", component: DKapitel3b },
  { id: "d-11-part2-divider", component: DChapterDivider },
  { id: "d-12-kapitel4", component: DKapitel4 },
  { id: "d-13-kapitel5", component: DKapitel5 },
  { id: "d-14-kapitel6", component: DKapitel6 },
  { id: "d-15-kapitel6b", component: DKapitel6b },
  { id: "d-16-part3-divider", component: DPart3Divider },
  { id: "d-17-kapitel7", component: DKapitel7 },
  { id: "d-18-kapitel8", component: DKapitel8 },
  { id: "d-19-part4-divider", component: DPart4Divider },
  { id: "d-20-kapitel9a", component: DKapitel9a },
  { id: "d-21-kapitel9b", component: DKapitel9b },
  { id: "d-22-recipe1", component: DRecipe },
  { id: "d-23-recipe2", component: DRecipe2 },
  { id: "d-24-recipe3", component: DRecipe3 },
  { id: "d-25-kapitel11a", component: DKapitel11a },
  { id: "d-26-kapitel11b", component: DKapitel11b },
  { id: "d-27-faq", component: DFAQ },
  { id: "d-28-anhang-intro", component: DAnhangIntro },
  { id: "d-29-trigger-check", component: DTriggerFoodCheck },
  { id: "d-30-notfallkarte", component: DNotfallkarte },
  { id: "d-31-einkaufsliste", component: DEinkaufslisteDruck },
  { id: "d-32-pantry", component: DPantry },
  { id: "d-33-ueber-chris", component: DUeberChris },
  { id: "d-34-schlusswort", component: DSchlusswort },
  { id: "d-35-backmatter", component: DBackmatter },
];

export const RemotionRoot: React.FC = () => (
  <>
    {stills.map(({ id, component }) => (
      <Still key={id} id={id} component={component} width={PAGE_WIDTH} height={PAGE_HEIGHT} />
    ))}
  </>
);
